#!/usr/bin/env python3
"""Turn a k6 summary and a gateway scrape into one report.

Two sources, on purpose. k6 knows what a producer saw; the gateway knows what
it did with it. A load test carrying only the first cannot tell a fast gateway
from one that answers 202 and drops what it accepted -- so the report puts
`events accepted` next to `batches delivered` and `records buried`, and a run
where those disagree is a run that failed however good the latency looked.
"""
import io
import json
import os
import re
import sys
from datetime import datetime, timezone


def k6_value(data, metric, stat):
    m = data.get("metrics", {}).get(metric, {}).get("values", {})
    return m.get(stat, 0)


def scrape(text):
    """Parse the exposition into {(name, labels): value}."""
    out = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([a-zA-Z_:][a-zA-Z0-9_:]*)(\{[^}]*\})?\s+(-?[\d.eE+]+)$", line)
        if not m:
            continue
        name, labels, value = m.group(1), m.group(2) or "", m.group(3)
        try:
            out[(name, labels)] = float(value)
        except ValueError:
            pass
    return out


def total(series, name):
    return sum(v for (n, _), v in series.items() if n == name)


def by_label(series, name, label):
    """Sum a series grouped by one label's value."""
    out = {}
    for (n, labels), v in series.items():
        if n != name:
            continue
        m = re.search(label + r'="([^"]*)"', labels)
        if m:
            out[m.group(1)] = out.get(m.group(1), 0) + v
    return out


def main():
    results = sys.argv[1] if len(sys.argv) > 1 else "results"
    with io.open(os.path.join(results, "k6.json"), encoding="utf-8") as f:
        k6 = json.load(f)
    with io.open(os.path.join(results, "metrics.txt"), encoding="utf-8") as f:
        gw = scrape(f.read())
    meta = {}
    meta_path = os.path.join(results, "run.json")
    if os.path.exists(meta_path):
        with io.open(meta_path, encoding="utf-8") as f:
            meta = json.load(f)

    accepted = k6_value(k6, "brevis_events_accepted", "count")
    refused = k6_value(k6, "brevis_events_refused_503", "count")
    rejected = k6_value(k6, "brevis_events_rejected", "count")
    reqs = k6_value(k6, "http_reqs", "count")
    rate = k6_value(k6, "http_reqs", "rate")
    mib = k6_value(k6, "brevis_body_bytes", "count") / 1048576.0
    dur = k6.get("state", {}).get("testRunDurationMs", 0) / 1000.0

    received = total(gw, "brevis_gateway_events_received_total")
    buried = total(gw, "brevis_gateway_dead_letter_records_total")
    saturated = total(gw, "brevis_gateway_saturated_total")
    batches = by_label(gw, "brevis_gateway_batches_total", "outcome")
    triggers = by_label(gw, "brevis_gateway_flushes_total", "trigger")
    delivery_sum = total(gw, "brevis_gateway_delivery_seconds_sum")
    delivery_n = total(gw, "brevis_gateway_delivery_seconds_count")

    ev_rate = accepted / dur if dur else 0
    when = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    L = []
    w = L.append
    w("# Gateway benchmark")
    w("")
    w("Generated by `bench/run.sh`. Two sources: **k6** for what a producer")
    w("saw, and the gateway's own `/metrics` for what it did with it.")
    w("")
    w("| | |")
    w("|---|---|")
    w("| run | %s |" % when)
    w("| image | `%s` |" % meta.get("image", "(local build)"))
    w("| host | %s |" % meta.get("host", "unknown"))
    w("| destination | %s |" % meta.get("sink", "postgres (container)"))
    w("| duration | %.0fs |" % dur)
    w("")
    w("## What the producer saw")
    w("")
    w("| | |")
    w("|---|---:|")
    w("| requests | %d (%.0f/s) |" % (reqs, rate))
    w("| events accepted | **%d** (%.0f/s) |" % (accepted, ev_rate))
    w("| events refused (503) | %d |" % refused)
    w("| events rejected, per event | %d |" % rejected)
    w("| body sent | %.1f MiB |" % mib)
    w("")
    w("| latency | ms |")
    w("|---|---:|")
    for label, stat in [("p50", "med"), ("p90", "p(90)"), ("p95", "p(95)"),
                        ("p99", "p(99)"), ("max", "max")]:
        v = k6_value(k6, "http_req_duration", stat)
        # A stat k6 never computed comes back 0, which reads as a fast tail
        # rather than as a missing number. summaryTrendStats in the script
        # asks for all of these; saying so here is the belt.
        w("| %s | %s |" % (label, "%.1f" % v if v else "not computed"))
    w("")
    w("A `503` is not a failure here. It is the gateway refusing an event it")
    w("has nowhere to put, which is the honest answer and safe to retry: the")
    w("`ingestion_id` is a frozen function of the event, so the same body sent")
    w("again is the same record.")
    w("")
    w("## What the gateway did")
    w("")
    w("| | |")
    w("|---|---:|")
    w("| events received | %d |" % received)
    w("| batches delivered | %d |" % batches.get("delivered", 0))
    w("| batches retried | %d |" % batches.get("retried", 0))
    w("| batches buried | %d |" % batches.get("buried", 0))
    w("| records in the dead letter | **%d** |" % buried)
    w("| requests refused, buffer full | %d |" % saturated)
    if delivery_n:
        w("| mean delivery | %.0f ms |" % (1000.0 * delivery_sum / delivery_n))
    w("")
    if triggers:
        w("Flushes by what triggered them:")
        w("")
        w("| trigger | batches |")
        w("|---|---:|")
        for k in sorted(triggers):
            w("| `%s` | %d |" % (k, triggers[k]))
        w("")
    w("## The three have to agree")
    w("")
    rows = meta.get("rows_in_postgres", 0)
    w("| witness | events |")
    w("|---|---:|")
    w("| k6 was told `accepted` | %d |" % accepted)
    w("| the gateway counted received | %d |" % received)
    w("| rows in Postgres | %d |" % rows)
    w("| records in the dead letter | %d |" % buried)
    w("")
    if abs(accepted - received) < 1 and abs(received - rows) < 1 and buried == 0:
        w("**They agree.** Every event that was answered `202` is a row, and")
        w("nothing was buried. This is the only number on the page that cannot")
        w("be traded for speed: a gateway can always be made faster by")
        w("accepting more than it delivers.")
    else:
        w("**They do not agree, and that is the finding.** Look here before any")
        w("latency number: a gap between `accepted` and a row in the database")
        w("is an event a producer was told had landed. The dead letter should")
        w("account for the difference; if it does not, something dropped")
        w("silently and the run failed however good the percentiles look.")
    w("")
    w("The third witness matters. The first two are both the gateway's own")
    w("arithmetic -- one from the response it wrote, one from the counter it")
    w("incremented -- and a bug that lost events could keep them consistent")
    w("with each other. The database is the only one that did not take our")
    w("word for it.")
    w("")
    w("## What this does not measure")
    w("")
    w("- **Not BigQuery.** The destination is a Postgres in a container on the")
    w("  same kernel. A warehouse's load-job quota, its commit latency and its")
    w("  concurrency are not in these numbers and cannot be.")
    w("- **Not durability.** `durability: memory` is the only tier there is, so")
    w("  a `202` means accepted into RAM. This measures how fast that happens,")
    w("  never what survives a `SIGKILL`.")
    w("- **Not your hardware.** It ran on whatever machine produced the header")
    w("  above. Read it as a shape and a ratio, not as a capacity plan.")
    w("")
    sys.stdout.write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
